language: ruby

before_install:
  - mysql -e 'CREATE DATABASE hilfe_test;'

rvm:
  - 2.3.1

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:schema:load

script:
  - bundle exec rspec

services:
  - mysql
  
notifications:
  email: false
