default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: dbpassword
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: hilfe_development

test:
  <<: *default
  database: hilfe_test

production:
  <<: *default
  database: hilfe_production
  username: hilfe
  password: <%= ENV['HILFE_DATABASE_PASSWORD'] %>
